# config/queue.yml
default: &default
  dispatchers:
    - queues: ["*"]
      poll_interval: 0.5

  workers:
    - queues: ["default"]
      threads: 5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default